# 2. 선형대수 - 벡터와 행렬

## 2.1.벡터

**벡터(vector)**란?
* **물리학**에서는 크기와 방향을 가지는 어떠한 물리량.
<img src="./images/vector_basic.gif" width="300">
* **수학**적으로는 하나 이상의 숫자들을 묶어 놓은 것을 말하며, 공간 상의 한 위치를 표현하는데 주로 사용된다.

<img src="./images/points_in_a_plane.png" width="200" title="2D 공간">

<img src="./images/235-3D-vector.png" width="200" title="3D 공간">

5차원 공간의 행 벡터 (row vector)  $ \left[ \begin{matrix} 3, 7, 9, 5.6, 10 \end{matrix} \right] $.

5차원 공간의  열 벡터 (column vector) $ \left[
\begin{matrix}
3\\
7\\
9\\
5.6\\
10
\end{matrix}
\right] $


**특징 벡터(feature vector)** : 패턴 인식에서는 인식 대상이 되는 객체가 특징들로 표현되고, 특징들은 일정한 차원을 갖는 벡터로 표현된다. 이러한 벡터를 특징벡터라고 한다. 그리고 특징 벡터에 대한 대수학적인 계산을 위해서 특징 벡터를 행렬로 표현하여 N-차원 공간 상의 한 점의 데이터로 특징을 다루게 된다. 관례적으로 벡터 $  \mathbf{x}  $ 는 $N\times1$ 행렬(또는 열벡터)로 간주 한다.

$ \mathbf{x}  = \left[
\begin{matrix}
x_1\\ x_2\\ \vdots\\ x_N
\end{matrix}
\right] $

**벡터의 전치(transpose)** : 벡터의 전치란 $N\times1$행렬을 $1\times N$ 행렬로, 혹은 $1\times N$ 행렬을$N\times1$행렬로 행과 열을 바꾼 행렬을 의미하며, 벡터에 윗첨자 $^T$로 표시한다.

$$ \mathbf{x}^T = \left[ \begin{matrix} x_1, x_2, \cdots, x_N \end{matrix} \right] $$

**벡터의 크기(norm)** : 벡터의 크기는 원점에서 벡터 공간 상의 한 점까지의 거리를 말하며, 다음과 같이 정의한다. (유클리드 공간에서의 경우.)

$$ \| \mathbf{x} \| =\sqrt{\mathbf{x}^T \mathbf{x} } = \sqrt{x_1^2 + x_2^2 + \cdots + x_N^2}  = [ \sum_{k=1}^N x_k x_k ]^{1/2} $$

ex) 벡터 $\mathbf{x} = [ 3, 4 ]^T $의 크기(norm)는?  $ \sqrt{9+16} = \sqrt{25} = 5 $ 
    
ex) 벡터 $\mathbf{x} = [ 3, 4, 5, 6 ]^T $의 크기(norm)는?

In [70]:
import numpy as np
x = np.array([ 3, 4 ])
print("sqrt(dot(x,x)) = ", np.sqrt(np.dot(x,x)))
print("sqrt(sum(x*x)) = ", np.sqrt(np.sum(x*x)))        # 벡터 간의 연산은 요소별 연산이 수행된다.
print("norm(x) = ", np.linalg.norm(x))                  # using norm mathod in linalg(Linear-Algebra) package

sqrt(dot(x,x)) =  5.0
sqrt(sum(x*x)) =  5.0
norm(x) =  5.0


In [71]:
x = np.array([ 3, 4, 5, 6])
print("norm(x) = ", np.linalg.norm(x))   

norm(x) =  9.273618495495704


**단위 벡터 (unit vector)**: 벡터의 크기가 1인 벡터를 “단위(unit)”벡터라고 한다. 만약, 벡터 v가 0 이 아닌 벡터라면 v 방향의 단위벡터 u 는 다음과 같이 규정한다. 이렇게 주어진 벡터와 방향이 같은 단위벡터를 구하는 과정을 벡터의 정규화(normalization) 라고 한다. 
$$ \mathbf{u} = { 1 \over \|\mathbf{v}\| } \mathbf{v} $$

ex) 벡터 $\mathbf{x} = [ 3, 4 ]^T $ 방향의 단위벡터 **u** 는?  $\mathbf{u} = {1 \over \| \mathbf{v} \|} [ 3, 4 ] = {1 \over 5} [ 3, 4 ] = [ 3/5, 4/5] $ 

이때 단위벡터 **u**의 크기는? 1

ex) 벡터 $\mathbf{x} = [ 3, 4, 5, 6 ]^T $방향의 단위벡터 **u** 는?

In [72]:
v = np.array([3,4])
u = v / np.linalg.norm(v)
print(u)
print(np.linalg.norm(u))

[0.6 0.8]
1.0


In [73]:
v = np.array([ 3, 4, 5, 6])
u = v / np.linalg.norm(v)
print(u)

[0.32349832 0.43133109 0.53916387 0.64699664]


### 벡터의 곱셈

**스칼라 곱**: 임의의 벡터에 임의의 스칼라(실수)를 곱하는 것을 말하며, 다음과 같이 성분 별로 스칼라를 곱해주면 된다.

$ \mathbf{y}  = a \mathbf{x}  = \left[
\begin{matrix}
ax_1\\ ax_2\\ \vdots\\ ax_N
\end{matrix}
\right] $

Ex) 벡터 $\mathbf{x}=[3,4]^T$일 때 $\mathbf{y} = 5\mathbf{x}$ 는?   $[15, 20]$

In [74]:
x = np.array([ 3, 4 ])
y = 5 * x
print(y)

[15 20]


**내적 (inner product; dot product)**: 차원이 동일한 두 개의 벡터 x, y 에 대하여 대응되는 성분 별로 곱하여 합하는 것을 두 벡터의 “내적”이라 한다.그러므로 벡터 내적의 결과는 실수 스칼라이다.

$$ c = \langle \mathbf{x},\mathbf{y} \rangle = \mathbf{x} \cdot \mathbf{y} = \mathbf{x}^T \mathbf{y} = \sum_{i=1}^N x_i y_i $$

두 벡터 사이의 각 $\theta$가 주어질 경우, 내적 스칼라 c 는 다음과 같이 주어진다.

$$ c = \| \mathbf{x}\| \|\mathbf{y} \| \cos \theta  \text{ ,      where       } 0 < \theta < \pi $$

ex) 벡터 $\mathbf{x}=[3, 4]^T$ 와  $\mathbf{y}=[5, 6]^T$ 의 내적 $\langle \mathbf{x},\mathbf{y} \rangle$ 는? $15 + 24 = 39$

ex) 벡터 $\mathbf{x}=[1, 0]^T$ 와  $\mathbf{y}=[0, 1]^T$ 의 내적 $\langle \mathbf{x},\mathbf{y} \rangle$ 는? 0

In [75]:
x = np.array([3, 4])
y = np.array([5, 6])
np.dot(x,y)

39

In [76]:
x = np.array([1,0])
y = np.array([0,1])
np.dot(x,y)

0

**수직사영 (orthogonal projection)** : 벡터 **y**를 벡터 **x**로 사영(혹은 투영)을 취하면, 벡터 **x** 의 방향으로 어떠한 길이를 가지는 벡터가 만들어진다. 이 사영 벡터는 내적의 정의를 사용하여 다음과 같이 정의하는데, 여기서, $\mathbf{u_x}$ 는 **x** 와 같은 방향의 단위 벡터이다.

$$ \langle \mathbf{y}^T,\mathbf{u_x} \rangle \mathbf{u_x} = ( \|\mathbf{y}\| \cos \theta )\mathbf{u_x}$$

<img src="./images/orthogonal.png"  width="200" title="orthogonal">

(Ex) 벡터 $\mathbf{y}=[2, 4]^T$ 의 벡터 $\mathbf{x}=[4, 3]^T$ 방향으로의 사영은?

$ u_x = ({ 1 \over  \|x\| }) x = \left[
\begin{matrix}
4/5\\ 3/5
\end{matrix}
\right]$

$ \langle \mathbf{y}^T,\mathbf{u_x} \rangle \mathbf{u_x} = ([ 2, 4 ] 
\left[
\begin{matrix}
4/5\\ 3/5
\end{matrix}
\right] ) 
\left[
\begin{matrix}
4/5\\ 3/5
\end{matrix}
\right] = 4 \times \left[
\begin{matrix}
4/5\\ 3/5
\end{matrix}
\right] =  \left[
\begin{matrix}
16/5\\ 12/5
\end{matrix}
\right]$

(Ex) 벡터 $\mathbf{y}=[2, 4]^T$ 의 벡터 $\mathbf{x}=[1, 0]^T$ 방향으로의 사영은?

(Ex) 벡터 $\mathbf{y}=[2, 4]^T$ 의 벡터 $\mathbf{x}=[0, 1]^T$ 방향으로의 사영은?

만약에 두 벡터  $\mathbf{x}$와 $\mathbf{y}$가
* $\mathbf{x}^T\mathbf{y} = 0 $ 이면 두 벡터 $\mathbf{x}$ 와 $\mathbf{y}$는 수직/직교(orthogonal)라고 한다.
* $\mathbf{x}^T\mathbf{y} = 0 $ 이면서, $\|\mathbf{x}\| = \|\mathbf{y}\| = 1$ 이면,  두 벡터 $\mathbf{x}$ 와 $\mathbf{y}$는 정규직교(orthonormal)라고 한다.

### 선형결합

벡터집합 $x=\{x_1, x_2, ..., x_N\}$ 와 스칼라 계수집합 $\{a_1, a_2,...,a_N\}$ 과의 곱의 합으로 표현된 벡터 $\mathbf{y}$를 벡터 $\mathbf{x}$의 “선형결합(linear combination)”이라고 한다.

$$ \mathbf{y} = a_1 \mathbf{x_1} +a_2 \mathbf{x_2} + \cdots +a_N \mathbf{x_N} $$

$$ \left[
\begin{matrix}
2\\3\\5
\end{matrix}
\right] = 
2 \times \left[
\begin{matrix}
1\\2\\3
\end{matrix}
\right] + 1 \times \left[
\begin{matrix}
0\\3\\1
\end{matrix}
\right] -2  \times \left[
\begin{matrix}
0\\2\\1
\end{matrix}
\right] $$


#### 선형종속
만약, 벡터집합  $x=\{x_1, x_2, ..., x_N\}$ 이 아래의 식을 만족하는 모두 0 이 아닌 스칼라 계수집합 $\{a_1, a_2,...,a_N\}$ 이 존재한다면, 다시 말해서, 벡터 집합 중 적어도 하나를 다른 벡터들의 선형결합으로 표현할 수 있다면, 이 벡터 집합은 “선형종속(linearly dependent)”이라고 한다.

$$ a_1 \mathbf{x_1} +a_2 \mathbf{x_2} + \cdots +a_N \mathbf{x_N} = \sum_{i=1}^N a_i \mathbf{x_i} = 0$$

$$ \left[
\begin{matrix}
0\\0\\0
\end{matrix}
\right] = 
1 \times \left[
\begin{matrix}
2\\2\\4
\end{matrix}
\right] - 2 \times \left[
\begin{matrix}
2\\2\\3
\end{matrix}
\right] + 2  \times \left[
\begin{matrix}
1\\1\\1
\end{matrix}
\right] $$

#### 선형독립
만약, 위의 식을 만족하는 유일한 해가$a_k= 0, \forall k$ 이라면  $x=\{x_1, x_2, ..., x_N\}$ 는 “선형독립(linearly independent)” 이라고 한다.

$$ a_1 \mathbf{x_1} +a_2 \mathbf{x_2} + \cdots +a_N \mathbf{x_N} =0 \Rightarrow a_k = 0, \forall k$$

$$ \left[
\begin{matrix}
0\\0\\0
\end{matrix}
\right] = 
0 \times \left[
\begin{matrix}
1\\0\\0
\end{matrix}
\right] + 0 \times \left[
\begin{matrix}
0\\1\\0
\end{matrix}
\right] + 0  \times \left[
\begin{matrix}
0\\0\\1
\end{matrix}
\right] $$

#### 기저집합
행렬 Nx1로 표현되는 모든 벡터를 표현할 수 있는 벡터의 집합을 “기저 벡터 집합”이라고 한다. 이때 임의의 벡터는 기저 벡터 집합을 통하여 Nx1 벡터 공간에 펼쳐(span)진다고 표현한다. 만약, 이 기저 집합이라면, 임의의 Nx1벡터 x는 다음과 같이 표현될 수 있다.

$$  \mathbf{x} = \sum_{i=1}^N c_i \mathbf{v_i} $$

$$ \left[
\begin{matrix}
3\\6\\9
\end{matrix}
\right] = 
3 \times \left[
\begin{matrix}
1\\0\\0
\end{matrix}
\right] + 6 \times \left[
\begin{matrix}
0\\1\\0
\end{matrix}
\right] + 9  \times \left[
\begin{matrix}
0\\0\\1
\end{matrix}
\right] $$

만약, 어떤 임의의 벡터 x가 {ui} 의 선형조합으로 표현이 되어질 수 있다면, 벡터집합 $\{u_1, u_2,...,u_N\}$ 은 벡터 공간에 대하여 기저(basis)를 형성한다고 말한다.

$$  \mathbf{x} = a_1 \mathbf{u_1} +a_2 \mathbf{u_2} + \cdots +a_N \mathbf{u_N}$$

계수  $\{a_1, a_2,...,a_N\}$를 기저 ${u_i}$ 에 따른 벡터 $\mathbf{x}$의 성분이라고 하고, 기저를 형성하기 위해서 ${u_i}$ 벡터들이 선형 독립인 것은 필요 충분한 조건이다.

직교(orthogonal) : $$  \mathbf{u_1}^T \mathbf{u_j} 
  \begin{cases}
   \neq 0 & \quad i = j \\
     =  0 & \quad i \neq j
  \end{cases}
$$
정규직교(orthonormal) : $$  \mathbf{u_1}^T \mathbf{u_j} 
  \begin{cases}
   = 1 & \quad i = j \\
     =  0 & \quad i \neq j
  \end{cases}
$$

#### 벡터공간 ( 또는 유클리드 공간)

* 모든 n차원 벡터들이 존재하는 n차원 공간을 “벡터 공간”이라고 한다.
* 벡터 공간은 실수에 의하여 벡터 덧셈과 벡터 곱셈에 대한 규칙에 닫혀있는 벡터 집합이다. 그러므로 임의의 두 벡터에 대한 덧셈과 곱셈을 통하여 해당 공간 내에 있는 새로운 벡터를 생성할 수 있다.
* n차원 공간 Rn 은 모두 선형독립인 n개의 n차원 벡터에 의해 생성될 수 있는데, 이때 n차원 공간 Rn 을“유클리드 n차원 공간”혹은“유클리드 공간”이라고 한다.

벡터간의 거리 : 벡터공간에 존재하는 두 점 사이의 거리(유클리디안 거리)는 두 점이 잊는 벡터의 길이로 다음과 같이 정의 된다.


$$ d_E (x,y) = | x - y | = [\sum_{k=1}^d (x_k - y_k)^2]^{1/2} $$

<img src="./images/vectors_distance.png" width="300" title="Distances between two vectors"  >

## 2.2 행렬 (Matrix)

* 행렬은 숫자들이 행과 열로 정리된 사각형 배열을 의미한다. 

$$  \begin{bmatrix}
 3 & 6 & 7 & 2 \\
 2 & 12 & 0 & 11 \\
 5 & -7 & -8 & 13 \\
 \end{bmatrix}
 $$

* 이러한 사각형 배열은 열벡터들의 배열로 생성될 수도 있다.

$$ \left[ 
 \begin{bmatrix}
 3  \\
 2  \\
 5  \\
 \end{bmatrix},
 \begin{bmatrix}
 6  \\
 12  \\
 -7  \\
 \end{bmatrix},
 \begin{bmatrix}
 7  \\
 0  \\
 8  \\
 \end{bmatrix},
 \begin{bmatrix}
 2  \\
 11  \\
 13  \\
 \end{bmatrix}
 \right]
 $$

* 행렬의 차원(또는 크기)은 (행의 개수) x (열의 개수) 로 표현한다. (예 위의 행렬은 3x4 의 크기를 갖는다)

* 다양한 형태 또는 특성에 따른 행렬의 종류는 다음과 같다.


**정방행렬 (square matrix)**: 행의 수와 열의 수가 동일한 행렬

**대각행렬 (diagonal matrix)**: 행렬의 대각 성분을 제외하고는 모두 0인 행렬, 모든 대각행렬은 정방 행렬이다.

$$ A = 
 \begin{bmatrix}
 3 &0 &0 \\
 0 &6 & 0 \\
 0 & 0 &-2 
 \end{bmatrix}
 $$

**스칼라행렬** : 대각 성분이 모두 같고, 비대각 성분이 모두 0인 정방행렬로, 다른 행렬에 곱하면, 그 효과가 스칼라를 곱한 것과 같아진다.
$$ B = 
 \begin{bmatrix}
 5 &0 &0 \\
 0 &5 & 0 \\
 0 & 0 &5 
 \end{bmatrix}
 $$

**항등 행렬** 혹은 **단위 행렬 ( identity matrix )** : 대각 성분이 모두 1 이고, 그 밖의 성분이 모두 0인 정방행렬
$$ I = 
 \begin{bmatrix}
 1 &0 &0 \\
 0 &1& 0 \\
 0 & 0 &1 
 \end{bmatrix}
 $$
 
 단위행렬은 임의의 행렬의 왼쪽 또는 오른쪽에 곱해도, 그 행렬 값에 영향을 주지 않는다.
 
 $$ IA = AI = A $$
 $$AIB = AB = ABI $$

**대칭 행렬 (symmetry matrix)** : 대각선을 축으로 모든 성분이 대칭되는 행렬
$$ S = 
 \begin{bmatrix}
 1 &4 &5 \\
 4 &2& 6 \\
 5 & 6 &3
 \end{bmatrix}
 $$
 
 $$ S = S^T $$

**영 행렬**: 
모든 구성 성분이 0인 행렬

**직교 행렬**:
주어진 행렬 A가 정방행렬일 때, $\mathbf{A}\mathbf{A}^T=\mathbf{I}$ 를 만족하는 행렬

$$ \mathbf{A}\mathbf{A}^T = 
 \begin{bmatrix}
  <\mathbf{x_1,x_1}> & 0 & \cdots & 0 \\
  0 & <\mathbf{x_2, x_2}>& \cdots & 0 \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  0 & 0& \cdots & <\mathbf{x_N, x_N}>
 \end{bmatrix}
 $$
 
 **전치행렬 (transposed matrix)**

$$ \mathbf{A} = 
 \begin{bmatrix}
  a_{11} & a_{12} & \cdots & a_{1N} \\
  a_{21} & a_{22} & \cdots & a_{2N} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{M1} & a_{M2} & \cdots & a_{MN} 
 \end{bmatrix}
  \Rightarrow
\mathbf{A}^T = 
 \begin{bmatrix}
  a_{11} & a_{21} & \cdots & a_{M1} \\
  a_{12} & a_{22} & \cdots & a_{M2} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{1N} & a_{2N} & \cdots & a_{MN} 
 \end{bmatrix}
 $$

**행렬의 곱셈**
$$ \mathbf{AB} = 
 \begin{bmatrix}
  a_{11} & a_{12} & \cdots & a_{1D} \\
  a_{21} & a_{22} & \cdots & a_{2D} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{M1} & a_{M2} & \cdots & a_{MD} 
 \end{bmatrix}
 \begin{bmatrix}
  b_{11} & b_{12} & \cdots & b_{1N} \\
  b_{21} & b_{22} & \cdots & b_{2N} \\
  b_{31} & b_{32} & \cdots & b_{3N} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  b_{D1} & b_{D2} & \cdots & b_{DN} 
 \end{bmatrix}
 = 
 \begin{bmatrix}
  c_{11} & c_{21} & \cdots & c_{1N} \\
  c_{21} & c_{22} & \cdots & c_{2N} \\
  c_{31} & c_{32} & \cdots & c_{3N} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  c_{M1} & c_{M2} & \cdots & c_{MN} 
 \end{bmatrix}
 $$
where
$ c_{ij} =  <\mathbf{a_{1*},b_{*1}}>  = \sum_{k=1}^D a_{ik}b_{kj} $

In [3]:
import numpy as np
A = np.array( [[1,1,1],[2,2,2]] )
B = np.array( [[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3]] )
print(A)
print(B)
C = np.dot(A,B) # numpy에서 행렬곱셈은 dot()으로 수행한다.
print(C)

[[1 1 1]
 [2 2 2]]
[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]]
[[ 6  6  6  6  6]
 [12 12 12 12 12]]


**행렬의 트레이스(trace)** : 정방행렬에서 대각 성분의 합
$$ tr(A) = \sum_{k=1}^D a_{kk}$$

* $tr(A) = tr(A^T)$
* $tr(A+B) = tr(A) + tr(B) $
* $tr(AB) = tr(BA)$

행렬의 고유값 문제에서 고유근을 구할 때 매우 중요한 역할을 함

In [4]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A_tr = np.trace(A)   # 1 + 5 + 9
print(A, A_tr)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 15


**행렬식 (determinant)** : 숫자들의 다차원적인 배열을 행렬이라고 한다면, 행렬식은 행렬을 어떠한 하나의 실수 값으로 표현한 것을 말한다. $d\times d$ 정방 행렬 $\mathbf{A}$에 대하여, 행렬식은 $|\mathbf{A}|$ 혹은 $\det \mathbf{A}$ 으로 표현하며 다음과 같이 계산된다.

$$ |\mathbf{A}| = \sum_{k=1}^D a_{ik}|\mathbf{A}_{ik}|(-1)^{k+1} $$
여기에서 $\mathbf{A}_{ik}$ 는 $\mathbf{A}$에서 $i$ 번째 행과 $k$ 번째 열을 제거하여 만든 부행렬(sub-matrix)을 말한다.

* 행렬식은 오직 정방 행렬에서만 정의된다.
* 행렬식의 값은 하나의 상수 즉, 임의의 실수이다.
* $n$차의 행렬식 $|\mathbf{A}_{n×n}|$은 n개의 행과 열의 위치가 서로 다른 성분들의 곱의 합으로 표현된다.

$$ |\mathbf{A}| = \left| \begin{matrix}
  a_{11} & a_{12}  \\
  a_{21} & a_{22} \\
 \end{matrix}\right| = a_{11}a_{22} - a_{21}a_{12} $$
 
$$ |\mathbf{A}| = \left| \begin{matrix}
  a_{11} & a_{12} & a_{13} \\
  a_{21} & a_{22} & a_{23} \\
  a_{31} & a_{32} & a_{33} \\
 \end{matrix}\right| = a_{11}a_{22}a_{33} + a_{12}a_{23}a_{31} + a_{13}a_{21}a_{32} - a_{13}a_{22}a_{31} - a_{11}a_{23}a_{32} - a_{12}a_{21}a_{33} $$

In [5]:
A = np.array([[4,2],[1,3]])
A_det = np.linalg.det(A)     #  (4x3) - (2x1)
print(A, A_det)

[[4 2]
 [1 3]] 10.000000000000002


**역행렬 (Inverse Matrix)**: 대수 연산에서 임의의 수를 곱하여 1이 될 때, 이를 "역수"라고 한다. 이를 행렬 대수에 적용하면, 가령 $\mathbf{AX} =\mathbf{I}$ 가 되는 $\mathbf{X}$ 가 존재할 경우에 이 행렬 $\mathbf{X}$ 를 $\mathbf{A}$ 의 역행렬이라고 하며 $\mathbf{A}^{-1}$로 표현한다.

역행렬의 성질
* $\mathbf{AA}^{-1}=\mathbf{I}$,   $\mathbf{A}^{-1}\mathbf{A}=\mathbf{I}$
* $(\mathbf{A}^{-1})^T = (\mathbf{A}^T)^{-1}$
* $(\mathbf{AB})^{-1} = \mathbf{B}^{-1}\mathbf{A}^{-1}$

In [6]:
A =np.array([[1,2],[3,4]])
A_inv = np.linalg.inv(A)
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})
print("A = \n", A)
print("Inverse of A = \n", A_inv)
print("A * A_inv = \n", np.dot(A,A_inv))
print("A_inv * A = \n", np.dot(A_inv,A))

A = 
 [[1 2]
 [3 4]]
Inverse of A = 
 [[-2.000  1.000]
 [ 1.500 -0.500]]
A * A_inv = 
 [[ 1.000  0.000]
 [ 0.000  1.000]]
A_inv * A = 
 [[ 1.000  0.000]
 [ 0.000  1.000]]


**정부호 (positive-definite)** : 양의 실수(positive real number)와 유사한 성질을 갖는 행렬의 성질을 말하며, 만약, 모든 영이 아닌 $x$ 에 대하여 $\mathbf{x}^T \mathbf{Ax}> 0$ 의 조건을 만족한다면, 행렬 $\mathbf{A}$는 정부호 행렬 (positive-definite matrix)이라고 한다. $\mathbf{A} > 0$ 은 $\mathbf{A}$가 정부호임을 나타낸다.
$$ A = 
 \begin{bmatrix}
 3 &0 &0 \\
 0 &1 & 0 \\
 0 & 0 &2 
 \end{bmatrix}
 $$
 만약, $\mathbf{x^T} = [1, -3, 2] $ 라면
 $$ \mathbf{x^T} A  \mathbf{x} = 
 \begin{bmatrix}
 1 &-3 &2 \\
 \end{bmatrix}
 \begin{bmatrix}
 3 &0 &0 \\
 0 &1 & 0 \\
 0 & 0 &2 
 \end{bmatrix}
 \begin{bmatrix}
 1 \\
 -3 \\
 2 
 \end{bmatrix}
 = 3 + 9 + 8 = 20 > 0
 $$

만약 $\mathbf{x}^T \mathbf{Ax} \ge 0$ 라면, $\mathbf{A}$는 반정부호(positive semidefinite)라고 한다. **공분산 행렬은 정부호 행렬의 대표적인 예이다**.

### 고유치와 고유벡터

고유치와 고유벡터 행렬 $\mathbf{A}$가 $N\times N$의 정방행렬이고, $\mathbf{x}\ne 0$ 인 벡터 $\mathbf{x} \in R^N$ 가 존재할 때, 다음 관계를 만족하는 스칼라 $\lambda$를 행렬 $\mathbf{A}$의 **고유치(eigenvalue)**라 하고 벡터 $\mathbf{x}$ 는 $\lambda$에 대응하는 $\mathbf{A}$의 **고유벡터(eigenvector)**라고 한다.

$$ \mathbf{Ax} = \lambda \mathbf{x}$$

예를 들어,
$$
\begin{bmatrix}
 2 &3 \\
 2 &1 
 \end{bmatrix}
 \begin{bmatrix}
3 \\
2
 \end{bmatrix}
 =  \begin{bmatrix}
12 \\
8
 \end{bmatrix}
 = 
 4 \times
  \begin{bmatrix}
3\\
2
 \end{bmatrix}
 $$

**고유치의 계산**
$$ \mathbf{Ax} = \lambda \mathbf{x}$$
$$ \mathbf{Ax} - \lambda \mathbf{x} = 0 $$
$$ (\mathbf{A} - \lambda \mathbf{I} ) \mathbf{x} = 0 $$
$$ \Rightarrow \mathbf{x} = 0 \quad \text{ or } \quad 
(\mathbf{A} - \lambda \mathbf{I} ) = 0 $$

$(\mathbf{A} - \lambda \mathbf{I} ) \mathbf{x} = 0$ 에서 $\mathbf{x}=0$ 이 아닌 해를 얻는 유일한 경우는 $(\mathbf{A} - \lambda \mathbf{I}) $ 가 정칙행렬 (singular matrix)인 경우이며, 이를 만족하는 필요충분조건은 $|\mathbf{A} - \lambda \mathbf{I} |=0$ 이고, 이 때 $\mathbf{x}\ne 0$인 해가 존재하게 된다.
여기에서 $|\mathbf{A} - \lambda \mathbf{I} |=0$ 를 $\mathbf{A}$의 특성방정식이라고 한다.

$$ (\mathbf{A} - \lambda \mathbf{I}) = 0 \Rightarrow
|\mathbf{A} - \lambda \mathbf{I} |= 0 \Rightarrow 
\lambda^N + a_1 \lambda^{N-1} + \cdots + a_{N-1} \lambda + a_N = 0 $$

$\mathbf{A}$ 를 $N\times N$ 행렬이라 하고, $\lambda$을 $\mathbf{A}$의 **고유값**이라고 한다. $\lambda$ 에 대응하는 모든 **고유 벡터**의 집합은 영벡터와 함께 $R^N$ 의 부분공간을 이룬다. 이 부분 공간을 $\mathbf{A}$의 **고유공간(eigenspace)**이라고 한다.



**고유치와 고유벡터의 성질**

* **대각행렬**의 고유치는 대각 성분 값이다.
* **삼각행렬**의 고유치는 이 행렬 대각 성분 값이다.
* 벡터 $\mathbf{x}$ 가 행렬 $\mathbf{A}$의 고유 벡터이면 벡터 $\mathbf{x}$의 스칼라 곱인 $k\mathbf{x}$도 고유 벡터이다.
* **전치**하여도 고유치는 변하지 않는다. 즉, 행렬 $\mathbf{A}$의 고유치와 전치행렬 $\mathbf{A}^T$의 고유치는
동일하다.
* **역행렬**의 고유치는 원래 행렬의 고유치의 역수가 된다.
* 행렬 $\mathbf{A}$의 **모든 고유치의 곱**은 $\mathbf{A}$의 행렬식과 같다.
* 서로 다른 고유치와 관련된 고유 벡터는 선형독립이다.
* **실수 대칭 행렬**의 고유 벡터는 서로 직교한다.
* **실수 대칭 행렬**의 고유치 또한 실수이다.
* 만약 $\mathbf{A}$가 양의 정부호 행렬이라면 모든 고유치는 양수이다.


In [12]:
A = np.array([[1,2,3], [6,5,4], [9,8,7]])
W, V = np.linalg.eig(A)
print('eigenvalue of A',W)  # 고유값으로 구성된 벡터
print(V)  # 고유벡터로 구성된 행렬
print('=='*20)

W, V = np.linalg.eig(np.transpose(A))
print('eigenvalue of A^T',W)  # 전치된 행렬의 고유값은 이전의 행렬의 고유값과 같다.
print(V)
print('=='*20)

A = np.array([[1,0,0], [0,2,0], [0,0,3]])
W, V = np.linalg.eig(A)
print(W)  # 대각행렬의 고유값은 대각성분
print(V)
print('=='*20)

W, V = np.linalg.eig(np.linalg.inv(A))
print(W) # 역행렬의 고유값은 원래 행렬의 고유값의 역수
print(V)

eigenvalue of A [ 14.639 -1.639 -0.000]
[[ 0.255  0.789  0.408]
 [ 0.502 -0.493 -0.816]
 [ 0.826 -0.366  0.408]]
eigenvalue of A^T [ 14.639 -1.639  0.000]
[[ 0.611  0.880 -0.239]
 [ 0.577  0.233 -0.796]
 [ 0.542 -0.414  0.557]]
[ 1.000  2.000  3.000]
[[ 1.000  0.000  0.000]
 [ 0.000  1.000  0.000]
 [ 0.000  0.000  1.000]]
[ 1.000  0.500  0.333]
[[ 1.000  0.000  0.000]
 [ 0.000  1.000  0.000]
 [ 0.000  0.000  1.000]]


## 2.3 선형변환

선형 변환이란 벡터공간 $R^N$ 으로부터 벡터공간  $R^M$ 상으로 매핑하는 것을 말하며, 행렬로는 다음과 같이 표현된다. 벡터 $ \mathbf{x} \in R^N$가 주어질 때,  $R^M$ 상에 대응되는 벡터  $\mathbf{y}$ 는 다음과 같이 계산된다.

$$ 
\begin{bmatrix}
  y_{1} \\
  y_{2}  \\
  \vdots  \\
  y_{M}
 \end{bmatrix}
 =
 \begin{bmatrix}
  a_{11} & a_{12} & a_{13} & \cdots & a_{1N} \\
  a_{21} & a_{22} & a_{23} & \cdots & a_{2N} \\
  \vdots  & \vdots  & \vdots & \ddots & \vdots \\
  a_{M1} & a_{M2} & a_{M3} & \cdots & a_{MN} 
 \end{bmatrix}
 \begin{bmatrix}
  x_{1} \\
  x_{2}  \\
  x_{3} \\
    \vdots  \\
  x_{N}
 \end{bmatrix}
 $$

선형 변환이 이루어지는 두 벡터 공간의 차원을 같을 필요는 없다. 패턴인식에서는 선형변환을 통하여 **특징벡터의 차원을 축소하는데 이용**한다. 

선형변환 행렬이 정방 행렬 $\mathbf{A}$이고 $\mathbf{AA}^T = \mathbf{A}^T\mathbf{A} = \mathbf{I}$ 일 때, 정규직교 한다고 말한다. 정규직교이면 $\mathbf{A}^T = \mathbf{A}^{-1}$ 이다. 특히 정규직교 변환하게 되면 아래와 같이 벡터의 크기를 보존하는 성질을 가짐을 알 수 있다.

$$ |\mathbf{y}| = \sqrt{\mathbf{y}^T\mathbf{y}} = 
\sqrt{(\mathbf{Ax})^T (\mathbf{Ax}) } = 
\sqrt{ \mathbf{x}^T \mathbf{A}^T \mathbf{Ax}} =
\sqrt{ \mathbf{x}^T\mathbf{x} } = |\mathbf{x}| $$

이때, 정규직교 변환의 행 벡터들 $(\mathbf{a_1,a_2, \cdots,a_N})$는 정규직교 기저벡터집합을 형성한다.

$$ \mathbf{y}_{M\times 1} = 
\begin{bmatrix}
 \leftarrow & \mathbf{a}_{1} & \rightarrow \\
 \leftarrow & \mathbf{a}_{2} & \rightarrow \\
 \vdots \\
 \leftarrow & \mathbf{a}_{N} & \rightarrow \\
 \end{bmatrix}
 \mathbf{x}_{N\times 1}
 \quad
 \text{with}
 \quad
 \mathbf{a}_i^T \mathbf{a}_j =   \begin{cases}
    0 & \quad i \ne j \\
    1 & \quad i =  j
  \end{cases}
 $$



주어진 행렬 A가 선형 변환이라면, 고유벡터(eigenvector)는 벡터공간에서의 불변 (invariant) 방향을 나타낸다.

A에 의한 변환 시에, 고유벡터(eigenvector) $\mathbf{v}$
로 정의되는 방향에 놓인 어떤 점들도 그대로 그 방향으로 놓이게 되며, 그 크기는 해당하는 고유치(eigenvalue) 로 곱해지게 된다.
<img src="images/eigenvector.png" width="250">

예를 들어, Z 축에 대하여 3차원 벡터를 회전하는 변환 A는 벡터 $[0, 0, 1]$을 유일한 고유 벡터로 갖게 되며 해당하는 고유치는 1이 된다.
$$ A = 
 \begin{bmatrix}
 \cos\beta &-\sin\beta &0 \\
 \sin\beta & \cos\beta & 0 \\
 0 & 0 &1 
 \end{bmatrix}
 $$

<img src="images/rotation_z.png" width="300">

[Prectices]

In [15]:
import numpy as np

# Vector operation

A = np.array([1, 2, 3, 4])
A_norm = np.linalg.norm(A)
print("A = ", A)
print("norm of A = ", A_norm)
B = 3*A
print("3 x A = ", B)

C = np.dot(A,B)
print("inner product of A & B = ", C)
D = np.outer(A, B)
print("outer product of A & B = \n",D)

A =  [1 2 3 4]
norm of A =  5.477225575051661
3 x A =  [ 3  6  9 12]
inner product of A & B =  90
outer product of A & B = 
 [[ 3  6  9 12]
 [ 6 12 18 24]
 [ 9 18 27 36]
 [12 24 36 48]]


In [81]:
# matrix operation

A = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(A,"\ntrace of A = ", np.trace(A))
print("determinant of A = ", np.linalg.det(A))
I = np.eye(4)  # Identity matrix
print(I)
Z = np.zeros((2,4))  # zeros matrix
print(Z)
O = np.ones((3,4)) # ones matrix
print(O)
D = np.array([2,3,6,1,3,5])
E = np.diag(D)  # diagonal matrix
print(E)

[[1 0 0]
 [0 1 0]
 [0 0 1]] 
trace of A =  3
determinant of A =  1.0
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2 0 0 0 0 0]
 [0 3 0 0 0 0]
 [0 0 6 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 3 0]
 [0 0 0 0 0 5]]


In [82]:
F = np.array([[1,2,3,], [4,5,6], [7,8,9]])
G = np.append(F, np.zeros((3,2)), axis=1)
H = np.append(np.zeros((2,3)),np.eye(2), axis=1)
J = np.append(G, H, axis=0)
print(G.shape, H.shape, J.shape, "\n", J)
W, V = np.linalg.eig(J)
print(W)
print(V)

(3, 5) (2, 5) (5, 5) 
 [[1. 2. 3. 0. 0.]
 [4. 5. 6. 0. 0.]
 [7. 8. 9. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15  1.00000000e+00
  1.00000000e+00]
[[-0.23197069 -0.78583024  0.40824829  0.          0.        ]
 [-0.52532209 -0.08675134 -0.81649658  0.          0.        ]
 [-0.8186735   0.61232756  0.40824829  0.          0.        ]
 [ 0.          0.          0.          1.          0.        ]
 [ 0.          0.          0.          0.          1.        ]]


[Questions]
1. 벡터 $a=[1,9,3,7,5]$ 의 크기를 구하시오.
2. 벡터 $b=[1,3,5]$ 와 $c=[2,4,6]$의 내적을 구하시오.
3. 행렬 $a=[1,2,3; 4,5,6; 7,8,9]$ 의 트레이스, 행렬식, 역행렬, 고유치 및 그에 해당하는 고유벡터들을 구하시오. 그리고 $b=a^T$ 에 대한 값들도 구해보시오.
4. 주어진 행렬 $a=[1,0,0,0; 0,2,0,0; 0,0,3,0; 0,0,0,5]$ 의 트레이스, 행렬식, 역행렬, 고유치 및 그에 해당하는 고유벡터들을 구하시오.
5. 주어진 행렬 $a=[1, 2, 3; 2, 1, 2; 3, 2, 1 ]$ 의 트레이스, 행렬식, 역행렬, 고유치 및 그에 해당하는 고유벡터들을 구하시오.