# Numpy

From [CS231n's Python Numpy Tutorial](http://cs231n.github.io/python-numpy-tutorial/)

Numpy는 Python 과학분야 컴퓨팅을 위한 핵심 라이브러리입니다. 고성능 다차원 배열 객체와 이러한 배열 작업을 위한 도구를 제공합니다. 이미 MATLAB에 익숙하다면, 이 튜토리얼이 Numpy를 시작하는데 유용할 것입니다.

## Arrays

* numpy 배열은 모두 같은 유형의 값들의 그리드이며, 음수가 아닌 정수의 튜플(tuple)에 의해 인덱싱됩니다.
* 차원의 수는 배열의 순위입니다.
* 배열의 모양은 각 차원을 따라 배열의 크기를 제공하는 정수의 튜플입니다.
* 우리는 중첩된 파이썬 리스트로부터 numpy 배열을 초기화 할 수 있고, 대괄호를 사용하여 요소에 접근 할 수 있습니다.

In [2]:
import numpy as np # import numpy library

a = np.array([1, 2, 3]) # list를 array(배열)로 만드는 method
print(a, type(a))
print(a.shape) # dimension 을 살펴보기 (shape는 tuple형식의 문법으로 표현됨)
# (3, ) = 1차원 array (2차원 부터는 ',' 뒤에 array의 크기(2 번째 방향으로의 길이)까지 표현)
print(a[0], a[1], a[2]) # a의 0, 1, 2 번쨰 index에 위치한 요소를 접근 
a[0] = 5 # 특정한 element를 수정하거나 고치고 싶을때 (a의 0번째 값을 5로 바꾸기)
print(a) # 1이 5로 바뀜

b = np.array([[1, 2, 3], [4, 5, 6]]) # 2차원 리스트를 줘서 2차원 array로 바꿈 (2 by 3 배열)
# 첫번째 행: [1, 2, 3]
# 두번째 행: [4, 5, 6]
print(b, b.shape) # (2, 3) = 2 by 3 배열 (tuple형식의 소괄호)
print(b[0, 0], b[0, 1], b[0, 2]) 
# b의 (첫번째 행, 첫번째 열), (첫번째 행, 두번째 열), (첫번째 행, 세번째 열) index에 위치한 요소를 접근

[1 2 3] <class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
[[1 2 3]
 [4 5 6]] (2, 3)
1 2 3


Numpy는 또한 배열을 생성하는 많은 함수를 제공합니다 :

In [10]:
a = np.zeros((2, 2)) # 0으로 가득차 있는 (2 by 2) 배열 
print(a)

b = np.ones((1, 2)) # 1로 가득차 있는 (1 by 2) 배열 
print(b)

c = np.full((2, 2), 7) # 7이라는 값으로 가득 채워진 (2 by 2) 배열 
print(c)

d = np.eye(2) # 단위행렬: 대각선 요소만 1이고 나머지는 0 인 (2 by 2) 행렬/배열
print(d) # 단위행렬은 항상 행과 열이 똑같다 (square matrix)

e = np.random.random((2, 2)) # np에서 지원되는 random이라는 object안에서 random값을 생성하는 method
print(e) # 랜덤한 값(0 과 1 사이의 실수)으로 채워진 (2 by 2) 배열 

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.96972102 0.78954997]
 [0.84464228 0.45572465]]


In [13]:
a = np.arange(5) # 0부터 4까지 숫자를 return하는 method (python 에서는 .range())
print(a)
b = np.arange(2, 3, 0.3) # 2와 3사이를 0.3간격으로 sampling한 실수값을 return (3 보다는 작음) 
print(b)
c = np.linspace(1., 4., 5) # 1과 4를 포함하는 5개의 등간격(equally-spaced)으로 sampling된 실수값을 return
print(c) # linspace (linear space의 약자)

[0 1 2 3 4]
[2.  2.3 2.6 2.9]
[1.   1.75 2.5  3.25 4.  ]


[여기에서](https://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation) 다른 배열 생성 방법을 읽을 수 있습니다.

## Array Indexing

Numpy는 배열에 색인을 생성하는 몇 가지 방법을 제공합니다.

**슬라이싱**: 파이썬 리스트와 마찬가지로, numpy 배열은 슬라이스 할 수 있습니다. 배열은 다차원 일 수 있으므로, 배열의 각 차원에 대해 슬라이스를 지정해야 합니다.

In [17]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]) # (3 by 4) 배열
print(a)

# 배열의 조각(slice)은 동일한 데이터에 대한 뷰이므로 수정하면 원래 배열이 수정됩니다.

b = a[:2, 1:3] # a의 첫번째 부터 두번째 행까지, 두번째 부터 세번째 열까지
print(b)
print(a[0,1]) # a의 첫번째 행, 두번째 열
b[0,0] = 77 # slicing을 해서 배열을 새로운 이름으로 할지라도 원래 배열을 그대로 가짐 (pointer 개념).
print(b)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
[[77  3]
 [ 6  7]]
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**정수 인덱싱**과 슬라이스 인덱싱을 혼용 할 수도 있습니다. 그러나 이렇게 하면 **원래 배열보다 낮은 순위의 배열**이 생성됩니다. 이것은 MATLAB이 배열 슬라이스를 처리하는 방식과 매우 다릅니다.

In [19]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

row_r1 = a[1, :] # a의 두번째 행 (정수 인덱싱)
row_r2 = a[1:2, :] # a의 두번째 행 (슬라이싱)
print(row_r1, row_r1.shape) # 정수 인덱싱을 하면 차원이 하나 줄어듬 (1차원 배열)
print(row_r2, row_r2.shape) # 행렬 형태 (2차원 행렬)

col_r1 = a[:, 1] # a의 두번째 열 (정수 인덱싱)
col_r2 = a[:, 1:2] # a의 두번째 열 (슬라이싱)
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


**정수 배열 인덱싱**: 슬라이싱을 사용하여 numpy 배열로 인덱싱 할 때, 결과 배열 뷰는 항상 원래 배열의 하위 배열이 됩니다. 반대로 정수 배열 인덱싱을 사용하면, 다른 배열의 데이터를 사용하여 임의의 배열을 구성 할 수 있습니다. 다음은 그 예입니다.

In [24]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
print(a[[0, 1 ,2], [0, 1, 0]]) # 특정한 element를 뽑기
print(np.array([a[0, 0], a[1, 1], a[2, 0]])) # 특정한 element를 뽑아서 배열로 만들어줌
print(a[[0,0], [1,1]])
print(np.array([a[0, 1], a[0, 1]]))

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[1 4 5]
[2 2]
[2 2]


정수 배열 인덱싱을 사용하는 유용한 트릭은 행렬의 각 행에서 하나의 요소를 선택하거나 변경하는 것입니다.

In [28]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]) # (4 by 4) 배열
print(a)
b = np.array([0, 2, 0, 1]) # a의 특정한 element 4개를 뽑아낼때 사용할 index 번호
print(b)
print(a[np.arange(4), b]) # a[0, 0], a[1, 2], a[2, 0], a[3, 1]를 뽑아내기
a[np.arange(4), b] += 10 # a[0, 0], a[1, 2], a[2, 0], a[3, 1]를 10만큼 더함
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[0 2 0 1]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


**부울 배열 인덱싱** : 부울 배열 인덱싱을 사용하면 배열의 임의 요소를 선택할 수 있습니다. 이 유형의 인덱싱은 일부 조건을 충족하는 배열 요소를 선택하는 데 자주 사용됩니다. 다음은 그 예입니다.

In [32]:
# 부울 배열 인덱싱: 배열 안에 부울값만 너놓고 True 값만 뽑아내기
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
# 부울값으로 인덱스를 갖고있는 배열
bool_idx = (a > 2) # a라는 배열에 2보다 큰 값들을 찾아서 그 값들의 부울 값 (True or False)
print(bool_idx)
print(a[bool_idx]) # True인 값을 가지는 인덱스 위치의 값을 뽑아냄
print(a[a>2])

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


간단히하기 위해 numpy 배열 인덱싱에 대한 많은 세부 사항을 생략했습니다.
더 많은 것을 알고 싶다면 [여기 문서](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)를 읽어야합니다.

## Datatype

각 numpy 배열은 동일한 유형의 요소 그리드입니다. 

Numpy는 배열을 생성하는 데 사용할 수 있는 많은 수의 데이터 유형을 제공합니다.

Numpy는 배열을 만들 때 데이터 유형을 추측하려 하지만, 배열을 생성하는 함수는 대개 데이터 유형을 명시적으로 지정하는 선택적 인수도 포함합니다. 

다음은 그 예입니다.

In [5]:
import numpy as np

x = np.array([1, 2])
print(x.dtype) # x가 갖고있는 값들의 datatype = 32bit자리 정수

x = np.array([1.0, 2.0])
print(x.dtype) # x가 갖고있는 값들의 datatype = 64bit자리 실수

x = np.array([1, 2], dtype = np.float64) # 직접 datatype 주기: datatype를 np에서 제공되는 float64 type으로 만듦
print(x.dtype)
print(x)

int64
float64
float64
[1. 2.]


## Array Math

기본 수학 함수는 배열에서 요소 단위로 작동하며, 연산자 오버로드와 numpy 모듈의 함수로 사용할 수 있습니다.

In [9]:
x = np.array([[1, 2], [3, 4]], dtype = np.float64)
y = np.array([[5, 6], [7, 8]], dtype = np.float64)

print(x, y)

print(x + y) # 해당 요소들끼리의 덧셈
print(np.add(x, y)) # x와 y를 더해준 값

print(x - y) # 해당 요소들끼리의 뺄셈
print(np.subtract(x, y)) # x와 y를 뺀 값

print(x * y) # 해당 요소들끼리의 곱셈
print(np.multiply(x, y)) # x와 y를 곱한 값

[[1. 2.]
 [3. 4.]] [[5. 6.]
 [7. 8.]]
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [11]:
print(x / y) # 해당 요소들끼리의 나눗셈
print(np.divide(x, y)) # x와 y를 나눈 값

print(np.sqrt(x)) # 해당 요소들의 제곱근

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


MATLAB와 달리 *는 행렬 곱셈이 아닌 요소별 곱셈입니다. 대신

* 벡터의 inner product를 계산하고,
* 벡터에 행렬을 곱하고,
* 행렬과 행렬을 곱하기 위해

dot 함수를 사용합니다. dot는 numpy 모듈의 함수와 배열 객체의 인스턴스 메서드로 사용할 수 있습니다.

In [17]:
x = np.array([[1, 2], [3, 4]]) # 2 by 2 행렬
y = np.array([[5, 6], [7, 8]]) # 2 by 2 행렬
print(x)
print(y)

v = np.array([9, 10]) # 1 by 2 벡터 (1-dimensional array)
w = np.array([11, 12]) # 1 by 2 벡터 (1-dimensional array)
print(v, w)

# 벡터와 벡터의 곱 
print(v.dot(w)) # v와 w의 dot product = (9 * 11 + 10 * 12)
print(np.dot(v, w))

# 벡터와 행렬의 곱
print(x.dot(v)) # x와 v의 dot product = [(1 * 9 + 2 * 10), (3 * 9 + 4 * 10)]
print(np.dot(x, v))

# 행렬 행렬의 곱
print(x.dot(y)) # x와 y의 dot product = [[(1 * 5 + 2 * 7), (1 * 6 + 2 * 8)], [(3 * 5 + 4 * 7), (3 * 6 + 4 * 8)]]
print(np.dot(x, y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[ 9 10] [11 12]
219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy는 배열에 대하여 계산을 수행하는 데 유용한 많은 함수을 제공합니다. 가장 유용한 것 중 하나가 sum입니다.

In [20]:
x = np.array([[1, 2], [3, 4]])
print(np.sum(x)) # 모든 요소를 더한 값 (1 + 2 + 3 + 4)
print(np.sum(x, axis = 0)) # 행 (0번째) 방향으로 더하기
print(np.sum(x, axis = 1)) # 열 (1번째) 방향으로 더하기

10
[4 6]
[3 7]


numpy가 제공하는 수학 함수의 전체 목록은 [여기](https://docs.scipy.org/doc/numpy/reference/routines.math.html)에서 찾을 수 있습니다.

배열을 사용하여 수학 함수를 계산하는 것 외에도 배열의 데이터를 변형하거나 조작해야하는 경우가 자주 있습니다.

이 유형의 연산 중 가장 간단한 예제는 행렬을 transpose 하는 것입니다. 행렬을 transpose 하려면 단순히 배열 객체의 T 속성을 사용하십시오.

In [23]:
x = np.array([[1, 2], [3, 4]]) # 행렬
print(x)
print(x.T) # 행과 열의 값이 뒤바뀜

v = np.array([1, 2, 3]) # 1차원 벡터
print(v)
print(v.T) # 벡터는 transpose해도 똑같은 하나의 행으로 나타남

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


두 배열의 행렬 곱에 numpy.matmul() 함수를 사용합니다. 동작은 다음과 같은 방식으로 인수에 따라 다릅니다.

* 두 인수가 2-D 이면 기존 행렬처럼 곱 해집니다.
* 두 인수 중 하나가 N-차원(N>2) 이면, 마지막 두 인덱스에 있는 행렬 스택으로 처리되어 그에 따라 브로드캐스팅됩니다.
* 첫 번째 인수가 1-D 이면, 차원에 1을 선행 (prepending) 하여 행렬로 승격됩니다. 행렬 곱셈 후 앞에 붙인 1이 제거됩니다.
* 두 번째 인수가 1-D 이면, 차원에 1을 추가 (appending) 하여 행렬로 승격됩니다. 행렬 곱셈 후에 추가 된 1이 제거됩니다.

matmul 함수는 Python 3.5에서 소개 된 @ 연산자의 의미를 구현합니다 .

In [53]:
import numpy as np

a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.matmul(a, b) # c = a @ b

array([[4, 1],
       [2, 2]])

In [55]:
a = [[1, 0], [0, 1]]
b = [1, 2]
print(np.matmul(a, b))
print(np.matmul(b, a))

[1 2]
[1 2]


In [56]:
a = np.arange(2 * 2 * 4).reshape((2, 2, 4))
b = np.arange(2 * 2 * 4).reshape((2, 4, 2))
np.matmul(a, b).shape                        # ???
np.matmul(a, b)[0, 1, 1]                     # ???
sum(a[0, 1, :] * b[0 , :, 1])                # ???

98

In [57]:
np.matmul([1, 2], 3)  #  주의 !!!  Error

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

열 벡터(1-D 배열)와 행 벡터(1-D 배열)의 곱셈은 np.outer() 로 수행한다. 

In [5]:
a = np.array(np.arange(1,7))
b = np.array(np.arange(1,4))
print(np.outer(a,b))
print(np.outer(b,a))

[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]]


Numpy는 배열 조작을 위한 많은 함수를 제공합니다. [여기](https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html)에서 전체 목록을 볼 수 있습니다.

## Matrix casting (obsolete)

연산자 * 가 행렬 연산으로 작동되게 해준다.

In [26]:
# 배열이 matrix형태로 casting됨
v = np.ones(3) # 길이가 3인 벡터
a = np.arange(1, 10).reshape((3,3)) # 1부터 9까지를 3 by 3 tuple형태의 2차원 배열로 만듦
print(v)
print(a)
print(v * a) # 배열 곱셈 (element 곱셈 연산) (벡터와 행렬의 연산이 아님)

A = np.matrix(a) # 벡터와 행렬의 곱셈을 위해 a배열을 행렬로 바꿔줌 (matrix casting)
print(v * A) # [[(1 * 1 + 1 * 4 + 1 * 7), (1 * 2 + 1 * 5 + 1 * 8), (1 * 3 + 1 * 6 + 1 * 9)]]

[1. 1. 1.]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[12. 15. 18.]]


## Broadcasting

브로드캐스팅은 산술 연산을 수행 할 때 numpy가 다른 모양의 배열로 작업 할 수 있게 해주는 강력한 메커니즘입니다. 

종종 우리는 더 작은 배열과 더 큰 배열을 가지며, 더 큰 배열에서 어떤 연산을 수행하기 위해 더 작은 배열을 여러 번 사용하려고 합니다.

예를 들어, 행렬의 각 행에 상수 벡터를 추가한다고 가정합니다. 우리는 다음과 같이 할 수 있습니다.

In [28]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]) # 3 by 4 2-dimensionl array
v = np.array([1, 0, 1]) # 1-dimensional vector
y = np.empty_like(x) # x와 같은 모양을 가지는 array

for i in range(4): # i = 0, 1, 2 ,3
    y[i, :] = x[i, :] + v # y 의 i번째 행의 모든값을 x 의 i번째 행의 모든값에 v가 추가된 값으로 채움

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


이것은 동작합니다. 그러나 행렬 x가 매우 클 경우 Python에서 명시적 루프를 계산하는 속도가 느려질 수 있습니다. 

행렬 x의 각 행에 벡터 v를 더하는 것은 v의 여러 복사본을 수직으로 쌓은 다음, 행렬 x와 v의 요소적 합계를 수행하여 행렬 vv를 만드는 것과 같습니다.

이 접근법은 다음과 같이 구현할 수 있습니다.

In [31]:
print(x)
print(v)
vv = np.tile(v, (4, 1)) # 1차원 벡터 v를 4개의 행으로 쌓음
print(vv)
y = x + vv
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
Numpy broadcasting는 실제로 v의 여러 복사본을 만들지 않고, 이 계산을 수행 할 수 있게 해줍니다. 
broadcasting을 사용하는 이 버전을 살펴보십시오.

In [34]:
print(x) # 4 by 3
print(v) # 1 by 3
# x와 v는 행의 갯수가 다르지만 열의 갯수가 같음
y = x + v # 각각의 행에 v가 더해짐 (broadcasting)
print(y) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


y = x + v 라인은 x가 shape (4, 3)이고 v가 shape (3)인데도 브로드케스팅으로 인해 작동합니다.

이 라인은 v가 실제로 shape (4, 3)를 가지는 것처럼 작동하며, 각 행은 v의 사본이고, 합계는 요소단위로 수행됩니다.

두 개의 배열을 함께 브로드캐스팅하면 다음 규칙이 적용됩니다.

* 배열의 rank가 같지 않으면, 두 모양이 같은 길이가 될 때까지 낮은 rank의 배열 모양 앞에 1로 하여 rank를 증가시킵니다.
* 두 배열은 차원에서 크기가 같거나, 배열 중 하나의 차원에 크기가 1인 경우에 차원에서 호환 가능하다고 합니다.
* 배열은 모든 차원에서 호환되는 경우 함께 브로드캐스팅될 수 있습니다.
* 브로드케스팅 후 각 배열은 두 개의 입력 배열의 요소 모양 최대 개수와 동일한 모양을 가진 것처럼 동작합니다.
* 한 배열의 크기가 1이고 다른 배열의 크기가 1보다 큰 차원에서 첫 번째 배열은 마치 해당 차원을 따라 복사 된 것처럼 작동합니다.

이 설명이 이해가 되지 않는 경우 [이 설명서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) 나 [이 설명](https://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc)을 읽으십시오.

브로드케스팅을 지원하는 기능을 보편적 기능이라고 합니다. [설명서](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs)에서 모든 범용 기능 목록을 찾을 수 있습니다.

일반적으로 브로드케스팅은
$$(m,1) \text{ matrix}  \quad +,-,*,/  \quad (1,1) \text{ matrix} \Rightarrow (m,1) \text{ matrix} $$
$$(1,m) \text{ matrix}  \quad +,-,*,/  \quad (1,1) \text{ matrix} \Rightarrow (1,m) \text{ matrix} $$
$$(m,n) \text{ matrix}  \quad +,-,*,/  \quad (1,n) \text{ matrix} \Rightarrow (m,n) \text{ matrix} $$
$$(m,n) \text{ matrix}  \quad +,-,*,/  \quad (m,1) \text{ matrix} \Rightarrow (m,n) \text{ matrix} $$

In [14]:
import numpy as np

x = np.array([1,2,3,4])
print(x + 100)                         # (1,4) + (1,1)
print(x + np.array([100,100,100,100])) # (1,4) + (1,4)

y = np.array([[1,2,3], [4,5,6]])
print(y + np.array([100, 200, 300]))                # (2,3)+ (1,3)
print(y + np.array([[100,200,300],[100,200,300]]))  # (2,3)+ (2,3)

print(y + np.array([[100],[200]]))                  # (2,3) + (2,1)
print(y + np.array([[100,100,100],[200,200,200]]))  # (2,3) + (2,3)

[101 102 103 104]
[101 102 103 104]
[101 102 103 104]
[[101 202 303]
 [104 205 306]]
[[101 202 303]
 [104 205 306]]
[[101 102 103]
 [204 205 206]]
[[101 102 103]
 [204 205 206]]


다음은 브로드케스팅의 일부 응용 프로그램입니다.

In [42]:
v = np.array([1, 2 ,3]) # 길이가 3인 3 by 1 벡터
w = np.array([4, 5]) # 길이가 2인 1 by 2 벡터
print(np.reshape(v, (3, 1)) * w) # 벡터 v를 3 by 1 열백터로 만들고 w를 곱함
             
x = np.array([[1, 2, 3], [4, 5, 6]]) # 2 by 3 행렬 (2차원 array)
print(x + v)                         # (2,3) + (1,3)

print((x.T + w).T) # 3 by 2 행렬 x와 w를 더하고 그 결과를 transpose

print(x + np.reshape(w, (2, 1))) # x에 2 by 1 열백터로 바뀐 x를 더함 

print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


Broadcasting은 일반적으로 코드를 보다 간결하고 빠르게 만들므로, 가능하면 이를 사용하려고 노력해야 합니다.

## Statistics

In [46]:
A = np.arange(25).reshape(5, 5) # 0부터 24까지의 숫자를 5 by 5 행렬로 만듦
print(A)
print(np.mean(A)) # 전체의 평균값을 계산 (0 부터 24까지 더한 값을 25로 나눔)
print(np.mean(A[:, 0])) # 0번째 열 방향으로 평균값을 계산 
print(A.mean(), A[:, 0].mean()) # 전체의 평균값, 첫번째 열의 평균값

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
12.0
10.0
12.0 10.0


In [51]:
print(np.std(A[:, 0]), np.var(A[:, 4])) # 첫번째 열의 표준 편차값, 다섯번째 열의 분산값
print(A.min(), A.min(axis = 1), A[:, 2].min()) # A의 가장 작은 값, 열 방향으로 가장 작은 값, 세번째 열에서 가장 작은 값
print(A.max(), A.max(axis = 1), A[3, :].max()) # A의 가장 큰 값, 열 방향으로 가장 큰 값, 네번째 행에서 가장 큰 값

7.0710678118654755 50.0
0 [ 0  5 10 15 20] 2
24 [ 4  9 14 19 24] 19


In [52]:
print(A.sum(), A[:, 1].prod()) # A에 있는 요소를 다 더한 값, A의 두번째 열의 요소를 다 곱한 값

300 22176
